### ISSUE TITLE
how to pass my own aetest.Options to aetest.NewInstance

### ISSUE THREAD

**Issue by tomoemon** [favclip/testerator#8]
I would like to pass my own aetest.Options to aetest.NewInstance.
They seem to be always fixed. I can't find the way to change them.

https://github.com/favclip/testerator/blob/master/testarator.go#L80-L84
```go
	opt := &aetest.Options{
		AppID: "unittest",
		StronglyConsistentDatastore: true,
		SuppressDevAppServerLog:     true,
	}
```

How do you think about adding `Options *aetest.Options` to Setup struct and using it in SpinUp?

**Comment by tomoemon** [comment]
solved my problem. I found that it doesn't need to change the Options.

**Comment by vvakame** [comment]
FYI: I just added https://github.com/favclip/testerator/commit/c967692c9c6519c9ab44484378e17cd17d05dd5c
